version: '3.8'

services:
  db:
    container_name: ${DB_NAME}
    image: postgres:15.4
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg:/var/lib/postgresql/data
    stdin_open: true
    tty: true

volumes:
  pg:
    external: false
