version: '3.8'

services:
  db:
    container_name: ${DB_NAME}
    image: postgres:15.4
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg:/var/lib/postgresql/data
    stdin_open: true
    tty: true

  cache:
    image: redis:7.2.2
    env_file:
      - .env
    ports:
      - "6379:6379"

  app:
    container_name: app
    depends_on:
      - db
      - cache
    build:
      context: .
      target: ${STAGE}
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env

volumes:
  pg:
    external: false
